# Generated by Django 6.0.2 on 2026-02-23 23:59

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contactpage_formfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, default='\n<p>\n  This website was developed as a practical example of a <strong>production-ready Wagtail CMS</strong> application.\n</p>\n<ul>\n  <li>Custom page models (Home, About, Blog, Contact)</li>\n  <li>Responsive Bootstrap layout</li>\n  <li>Editable content through the Wagtail admin panel</li>\n  <li>PostgreSQL database integration</li>\n  <li>Cloud deployment using Gunicorn and Render</li>\n</ul>\n<p>\n  The project demonstrates the core skills required for <strong>Django/Wagtail freelance development</strong>,\n  including CMS customization, template work, and deployment configuration.\n</p>\n'),
        ),
        migrations.AlterField(
            model_name='blogindexpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, default='\n<p>\n  Welcome to the blog. Here you can find short posts about Django, Wagtail, scraping, and deployment.\n</p>\n'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, default='\n<p>\n  Django and Wagtail together provide a powerful combination for building modern content-managed websites.\n  Wagtail offers a flexible CMS interface, while Django handles the backend logic and database structure.\n</p>\n<p>\n  This demo post exists to show a real blog workflow: create posts from the admin panel and publish them instantly.\n</p>\n'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, default='\n<p>\n  Feel free to get in touch using the form below.\n  This contact form is fully functional and managed through the Wagtail CMS.\n</p>\n<p>\n  I’m available for <strong>Django</strong>, <strong>Wagtail</strong>, and <strong>Python</strong> web development projects,\n  including small fixes, new features, and full website setups.\n</p>\n'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='thank_you_text',
            field=wagtail.fields.RichTextField(blank=True, default='\n<p>Thank you for your message! I will get back to you as soon as possible.</p>\n'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, default='\n<p class="lead">\n  This is a demonstration website built with <strong>Django</strong> and <strong>Wagtail CMS</strong>.\n  It showcases custom page templates, a blog, and a functional contact form.\n</p>\n<p>\n  The goal of this project is to demonstrate real-world backend development,\n  content management features, and cloud deployment in a clean and responsive layout.\n</p>\n'),
        ),
    ]
